version: "3.8"

services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile.spring
    ports:
      - "8012:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    container_name: arqwebv01-app
    restart: unless-stopped
