version: "3.8"

services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile.spring
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - nginx-network

networks:
  nginx-network:
    external: true
# docker teste
